### ISSUE TITLE
lap-pair error

### ISSUE THREAD

**Issue by aman19023** [gurumitts/pylutron-caseta#164]
Traceback (most recent call last):
  File "/home/okas/new_venv/lib/python3.12/site-packages/pylutron_caseta/pairing.py", line 55, in async_read_json
    buffer = await self._reader.readline()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/streams.py", line 568, in readline
    line = await self.readuntil(sep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/streams.py", line 660, in readuntil
    await self._wait_for_data('readuntil')
  File "/usr/lib/python3.12/asyncio/streams.py", line 545, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/okas/new_venv/bin/lap-pair", line 8, in <module>
    sys.exit(lap_pair())

**Comment by mdonoughe** [comment]
Did you cancel it by pressing control C?
