### ISSUE TITLE
lap-pair error for Lutron Caséta Smart Hub (L-BDG2-WH)

### ISSUE THREAD

**Issue by ajaymajgaonkar** [gurumitts/pylutron-caseta#174]
Traceback (most recent call last):
  File "/usr/local/bin/lap-pair", line 8, in <module>
    sys.exit(lap_pair())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pylutron_caseta/cli.py", line 31, in wrapper
    return asyncio.run(main(*args, **kwargs))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/pylutron_caseta/cli.py", line 132, in lap_pair
    data = await async_pair(address, _ready)
  File "/usr/local/lib/python3.10/dist-packages/pylutron_caseta/pairing.py", line 83, in async_pair
    cert_pem, ca_pem = await _async_generate_certificate(
  File "/usr/local/lib/python3.10/dist-packages/pylutron_caseta/pairing.py", line 124, in _async_generate_certificate
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.0.235', 8083)

**Comment by wdfrench13** [comment]
I had this same issue. I was able to fix it by opening all traffic across my VLANs to the Lutron IP addresses. You may be filtering traffic for your device/port.

**Comment by mdonoughe** [comment]
Errors like this are caused by network problems, most commonly using an incorrect IP address, but it could be caused by many different things outside the scope of this library.
