### ISSUE TITLE
get_lutron_cert.py remote_signs_app_certificate error

### ISSUE THREAD

**Issue by hdemel** [gurumitts/pylutron-caseta#27]
I'm unable to successfully run this script. I always get the following error:

```
Traceback (most recent call last):
  File "get_lutron_cert.py", line 78, in <module>
    with open('caseta.crt', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'caseta.crt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_lutron_cert.py", line 125, in <module>
    app_cert = pairing_response["remote_signs_app_certificate"]
KeyError: 'remote_signs_app_certificate'

```

I've tried running this on two separate Ubuntu Servers (18.04). Instructions in the script were followed exactly.  I've been able to run this before but as of today this doesn't work.

Any advice on how I can get this working?

**Comment by mdonoughe** [comment]
Are you using the script from this repo or the script on the Home Assistant documentation? The one on Home Assistant needs to be updated next time the Home Assistant integration is updated.

**Comment by mbrancato** [comment]
I get the same thing. When I enable debug with requests, I get the error below. It looks like the path `/api/v1/remotepairing/application/user` is not valid.

```
Open Browser and login at https://device-login.lutron.com/oauth/authorize?client_id=***************************************************************&redirect_uri=https%3A%2F%2Fdevice-login.lutron.com%2Flutron_app_oauth_redirect&response_type=code
Enter the URL (of the "error" page you got redirected to (or the code in the URL): ***************************************************************
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): device-login.lutron.com
send: b'POST /oauth/token HTTP/1.1\r\nHost: device-login.lutron.com\r\nUser-Agent: python-requests/2.18.4\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nContent-Length: 332\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\n'
send: b'code=***************************************************************&client_id=***************************************************************&client_secret=***************************************************************&redirect_uri=https%3A%2F%2Fdevice-login.lutron.com%2Flutron_app_oauth_redirect&grant_type=authorization_code'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: Cowboy
header: Date: Fri, 13 Dec 2019 12:29:21 GMT
header: Connection: keep-alive
header: Cache-Control: private, no-store
header: Pragma: no-cache
header: Content-Type: application/json; charset=utf-8
header: Etag: W/"*********************************"
header: X-Request-Id: ace7b3b5-1f3c-4995-ad55-63463454d59f
header: X-Runtime: 0.143709
header: Content-Length: 235
header: Via: 1.1 vegur
DEBUG:urllib3.connectionpool:https://device-login.lutron.com:443 "POST /oauth/token HTTP/1.1" 200 235
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): device-login.lutron.com
send: b'POST /api/v1/remotepairing/application/user HTTP/1.1\r\nHost: device-login.lutron.com\r\nUser-Agent: python-requests/2.18.4\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nX-DeviceType: Caseta,RA2Select\r\nAuthorization: Bearer ***************************************************************\r\nContent-Length: 1128\r\nContent-Type: application/json\r\n\r\n'
send: b'{"remote_signs_app_certificate_signing_request": "-----BEGIN CERTIFICATE REQUEST-----\\n*************\\n-----END CERTIFICATE REQUEST-----\\n"}'
reply: 'HTTP/1.1 404 Not Found\r\n'
header: Server: Cowboy
header: Date: Fri, 13 Dec 2019 12:29:21 GMT
header: Connection: keep-alive
header: X-Frame-Options: SAMEORIGIN
header: X-Xss-Protection: 1; mode=block
header: X-Content-Type-Options: nosniff
header: X-Download-Options: noopen
header: X-Permitted-Cross-Domain-Policies: none
header: Referrer-Policy: strict-origin-when-cross-origin
header: Content-Type: application/json; charset=utf-8
header: Cache-Control: no-cache
header: X-Request-Id: ***************************
header: X-Runtime: 0.011208
header: Content-Length: 2
header: Via: 1.1 vegur
DEBUG:urllib3.connectionpool:https://device-login.lutron.com:443 "POST /api/v1/remotepairing/application/user HTTP/1.1" 404 2
{}
Traceback (most recent call last):
  File "get_lutron_cert.py", line 92, in <module>
    with open('caseta.crt', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'caseta.crt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_lutron_cert.py", line 140, in <module>
    app_cert = pairing_response["remote_signs_app_certificate"]
KeyError: 'remote_signs_app_certificate'
```

**Comment by mdonoughe** [comment]
Try this script instead: https://github.com/mdonoughe/pylutron-caseta/blob/lap-pairing/get_lutron_cert.py

Note the different pip dependency in the comment at the top.

**Comment by mdonoughe** [comment]
Have you gotten to try the new script?
