### ISSUE TITLE
Support for multi-scene keypads

### ISSUE THREAD

**Issue by stappon** [gurumitts/pylutron-caseta#35]
I have [this Pico 4-button remote](https://www.prolighting.com/lutron-pico-4-button-kitchen-scene-wireless-remote-white.html) that triggers four different scenes. The associated scenes are defined from within the device settings in the app, not from the "Scenes" tab. They are also backed by a different smart bridge response format:
```
{
	'href': '/vbutton/4',
	'ButtonNumber': 1,
	'ProgrammingModel': {
		'href': '/programmingmodel/125'
	},
	'Parent': {
		'href': '/area/6'
	},
	'IsProgrammed': True,
	'Category': {
		'Type': 'Kitchen',
		'SubType': 'Bright'
	}
}
```

This causes the following error when loading scenes:
```
2019-09-08 01:58:38 ERROR (MainThread) [homeassistant.setup] Error during setup of component lutron_caseta
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 168, in _async_setup_component
    hass, processed_config
  File "/usr/src/homeassistant/homeassistant/components/lutron_caseta/__init__.py", line 53, in async_setup
    await bridge.connect()
  File "/usr/local/lib/python3.7/site-packages/pylutron_caseta/smartbridge.py", line 40, in connect
    yield from self._login()
  File "/usr/local/lib/python3.7/site-packages/pylutron_caseta/smartbridge.py", line 285, in _login
    yield from self._load_scenes()
  File "/usr/local/lib/python3.7/site-packages/pylutron_caseta/smartbridge.py", line 351, in _load_scenes
    scene_name = scene['Name']
KeyError: 'Name'
```

Also, the `/vbutton/N` numbers conflict with the `/virtualbutton/N` numbers of my normal lighting scenes, so in order to fully fix, I need to modify `activate_scene` to be aware of whether it's dealing with a `vbutton` or a `virtualbutton` and pass the corresponding URL.

I'm happy to make a pull request for this if desired! If making the full change is undesirable for some reason, at minimum I'd like to add a try/catch to skip scenes that cause this KeyError.

PS: The smart bridge unit tests all fail for me under Python 3.7. Updating them to async/await syntax makes them pass. Should I make a PR for that as well?

**Comment by swails** [comment]
See #40 for the fix to this.
