### ISSUE TITLE
component failed to setup with KeyError: 'Body'

### ISSUE THREAD

**Issue by guoyiang** [gurumitts/pylutron-caseta#48]
Caseta component setup failed after I upgraded to home assistant 0.108.0.dev20200330, with below exception. 
```
2020-03-31 18:41:26 ERROR (MainThread) [homeassistant.setup] Error during setup of component lutron_caseta
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 171, in _async_setup_component
    hass, processed_config
  File "/usr/src/homeassistant/homeassistant/components/lutron_caseta/__init__.py", line 53, in async_setup
    await bridge.connect()
  File "/usr/local/lib/python3.7/site-packages/pylutron_caseta/smartbridge.py", line 51, in connect
    await self._login()
  File "/usr/local/lib/python3.7/site-packages/pylutron_caseta/smartbridge.py", line 363, in _login
    await self._load_occupancy_groups()
  File "/usr/local/lib/python3.7/site-packages/pylutron_caseta/smartbridge.py", line 467, in _load_occupancy_groups
    for occgroup in occgroup_json["Body"]["OccupancyGroups"]:
KeyError: 'Body'
```

**Comment by swails** [comment]
Oops... I've never seen this fail before on my system (but my system also has occupancy sensors attached to it).

@mdonoughe, this should probably be merged and another release cut before HA 0.108 goes out the door?

**Comment by guoyiang** [comment]
I have a non-pro version Smart Bridge and i do not have occupancy sensors, maybe that's why it failed...

**Comment by swails** [comment]
I also have a non pro version. That’s why I needed to add support for occupancy sensors to this library.
