### ISSUE TITLE
Having trouble with Python 2 on Win7

### ISSUE THREAD

**Issue by toreupfeet** [gurumitts/pylutron-caseta#70]
I'm the noobiest around, so I might just be doing this incorrectly. I'm on Win7 with Python 2, and this my session:

```
C:\Python27\Scripts>pip install pyopenssl

C:\Python27\Scripts>python get_lutron_cert.py
get_lutron_cert.py:25: CryptographyDeprecationWarning: Python 2 is no longer sup
ported by the Python core team. Support for it is now deprecated in cryptography
, and will be removed in the next release.
  from cryptography import x509
Traceback (most recent call last):
  File "get_lutron_cert.py", line 38, in <module>
    [x509.NameAttribute(NameOID.COMMON_NAME, "get_lutron_cert.py")]
  File "C:\Python27\lib\site-packages\cryptography\x509\name.py", line 87, in __
init__
    raise TypeError("value argument must be a text type.")
TypeError: value argument must be a text type.

C:\Python27\Scripts>
```
I know very little and I'm honestly just knocking on the door to see if someone can nudge me in the right direction. I don't know where to go from here.

**Comment by mdonoughe** [comment]
Python 2 is not supported. You must use Python 3.7 or later.

**Comment by toreupfeet** [comment]
I see. Thank you for the response.
